### ISSUE TITLE
Missing type kind handling

### ISSUE THREAD

**Issue by jklmnn** [Componolit/Cappulada#32]
Add handling for missing type kinds:
 - [x] `TypeKind.ENUM`
 - [x] `TypeKind.DEPENDENTSIZEDARRAY`
   - Arrays with sizes defined by templates
 - [x] `TypeKind.CONSTANTARRAY`
   - Arrays with constant sizes
 - [x] `TypeKind.ULONGLONG`
 - [x] `TypeKind.INVALID`
   - Caused by typedefs of templates
 - [x] `TypeKind.MEMBERPOINTER`
 - [x] `TypeKind.AUTO`
   - handled by #84 

and missing type declaration handling:
 - [x] `CursorKind.STRUCT_DECL`
 - [x] `CursorKind.CLASS_TEMPLATE`
   - Caused by template instantiation with another template argument
 - [x] `CursorKind.ENUM_DECL`
 - [x] `CursorKind.TYPEDEF_DECL`

66f61491dd3f74864e82fd0b2dcf3aed1360179f introduced completeness checking for cursor children which added the following unhandled cursor kinds:
 - [x] `CursorKind.UNEXPOSED_DECL`
 - [x] `CursorKind.TEMPLATE_NON_TYPE_PARAMETER`
 - [x] `CursorKind.VAR_DECL`
   - Caused by global variable.

When generating bindings for the block session (see #72) the following errors occur:
 - [x] `CursorKind.DESTRUCTOR`
   - handled in #49
 - [x] `CursorKind.FUNCTION_TEMPLATE`
   - handled in #73
 - [x] `CursorKind.CONVERSION_FUNCTION`
   - caused by [cast implementation](https://en.cppreference.com/w/cpp/language/cast_operator)
   - handled in #74 
 - [x] `CursorKind.CLASS_TEMPLATE_PARTIAL_SPECIALIZATION`
   - handled in #77 
 - [x] `CursorKind.TYPE_ALIAS_DECL`
   - Type aliases in C++ are equivalent to typedefs (https://stackoverflow.com/a/10748056/4790678)
 - [x] `CursorKind.TYPE_REF`

**Comment by senier** [comment]
Here is an instance of `TypeKind.INVALID`:

```c++
template <typename A, typename B>                                                                                                                                                              
class Templ
{
   public:
      Templ() { };
      A element1;
      B element2;
};

template <typename ...Ts>
class Var
{
   public:
      Var() { };
      int element1;
};

class Cls
{
   public:
      Cls() { };
      int bar (Templ<char, int> p1, char p2) { };
      int foo (int p1, char p2) { };
      int baz (Templ<char, int> p1, Templ<char,char> p2) { };
      int var (Var<> p1, char p2) { };
};
```

The issue arises due to the variadic template.

```
Traceback (most recent call last):
  File "/home/alex/Documents/Componolit_GmbH/Devel/src/capdpa/tests/testmangling.py", line 44, in test_template
    functions = CXX("tests/data/test_template_mangling.h").ToIR(project="Capdpa").children[1].children
  File "capdpa/cxx.py", line 216, in ToIR
    children = self.__convert_children(self.translation_unit.cursor.get_children())
  File "capdpa/cxx.py", line 187, in __convert_children
    children.append(self.__convert_class(cursor))
  File "capdpa/cxx.py", line 59, in __convert_class
    children = self.__convert_children(cursor.get_children()))
  File "capdpa/cxx.py", line 196, in __convert_children
    children.append(self.__convert_function(cursor))
  File "capdpa/cxx.py", line 71, in __convert_function
    parameters = self.__convert_arguments(cursor.get_children()),
  File "capdpa/cxx.py", line 126, in __convert_arguments
    ptype = self.__convert_type(cursor.type)
  File "capdpa/cxx.py", line 102, in __convert_type
    arguments = [self.__convert_type(type_cursor.get_template_argument_type(i)) for i in range(targs)],
  File "capdpa/cxx.py", line 119, in __convert_type
    raise NotImplementedError("Unsupported type: {} (from {})".format(type_cursor.kind, type_cursor.spelling))
NotImplementedError: Unsupported type: TypeKind.INVALID (from )
```

**Comment by jklmnn** [comment]
Member pointer in C++ are function pointer that point to member functions of other classes. The speciality here is an "invisible" first argument to the parent class (see https://stackoverflow.com/a/43209187/4790678).
So a function pointer `void (A::*)()` resolves to `void (*)(A*)`.
For a template this makes the target of the template argument clear.
Instead of somehow resolving the name we just generate a function/procedure with the correct first argument. The template argument should be resolved automatically via the type resolving that is already existent (although the implementation for template functions in general is still missing).
