### ISSUE TITLE
Template name mangling

### ISSUE THREAD

**Issue by senier** [Componolit/Cappulada#46]
Implement mangling for template instance.

**Comment by senier** [comment]
Template instances are inserted into the IR with a special name directly after the template object, e.g. `A_T_int` for a template class `A` instantiated with `int`. The mangled symbol is wrong for those generated classes, as the name is different. Also, template arguments are encoded differently.

@jklmnn: How do we identify a class as template instance and how do we get the template it was instantiated from?

**Comment by jklmnn** [comment]
Afair there is currently no distinction between template instances and regular classes except their name. Yet it would be relatively easy to add an attribute (e.g. `instanceof`) which is set to `None` by default and set it to the template it has been instantiated from including the used template arguments (if this is required, too).

**Comment by jklmnn** [comment]
https://github.com/Componolit/capdpa/commit/157d60d61ab0fd7bb63b94dbc59baf7b5ee068ba should contain the information you require,. I did not test it though.

**Comment by senier** [comment]
Cool, thank you! Will try.

**Comment by senier** [comment]
A solution to #50 is required to implement and test mangling for templates that are instantiated with non-builtin types.

**Comment by senier** [comment]
Done.
