### ISSUE TITLE
Proper README

### ISSUE THREAD

**Issue by jklmnn** [Componolit/Cappulada#60]
Since we are going to present this project at FOSDEM and the repository is linked on the page for the talk we should add a proper README.

**Comment by jklmnn** [comment]
@senier I expanded the first example a little bit to use a template instead of a plain class (https://github.com/jklmnn/capdpa/commit/dad8dc5743ced2eb6d781f4d60f92f1d5d0710b8). I don't think it takes much more time to show and explain but would IMO show better that we're able to use complex features.

**Comment by senier** [comment]
I like that improvement very much. Would you mind updating the example in the README to the more advanced one, too?
