### ISSUE TITLE
Private nested classes

### ISSUE THREAD

**Issue by jklmnn** [Componolit/Cappulada#76]
Genode uses private classes. We currently don't have any procedure to handle those correctly. The correct solution would be to create a limited type and embed that into our class record.
@senier what do you think about that?

**Comment by jklmnn** [comment]
For private nested classes we only define a private type named `Private_<class name>_Class` that goes into the public record. The class itself is only defined as a record in the private part of the package. Functions etc. are not imported.

**Comment by jklmnn** [comment]
Since the separation of private and public classes does not fit well in the generator private classes will be only available as `Private_Records`. Those only represent the memory layout of a class and provide a private type in Ada.

**Comment by senier** [comment]
As discussed offline, we take the following approach:

1. A private type is generated in the public spec
2. The class and it's surrounding inline package are generated in the *private* part
3. The full declaration of the private type renames *package*.Class
